renamed setState and setDefautState to setView and setDefaultView
JonasKaad/SemesterProject-4 pull request #239
Opened 2022-05-20 12:10 UTC by VictorABoye

This renaming was done as it made more sense given that the class had been renamed from `IGameStateManager` to `IGameViewManager`.

2022-05-20 12:54 UTC, AlexanderNorup requested changes

2022-05-20 12:54 UTC, AlexanderNorup commented on Core/src/main/java/dk/sdu/mmmi/modulemon/managers/GameViewManager.java
>          currentGameState.init(this);
Please also change this variable name from `currentGameState` to `currentGameView`

2022-05-20 12:54 UTC, AlexanderNorup commented on Core/src/main/java/dk/sdu/mmmi/modulemon/managers/GameViewManager.java
> +    public void setView(IGameViewService state, boolean disposeCurrent) {
`state` -> `view`

2022-05-23 08:54 UTC, SebMon approved these changes

2022-05-23 09:01 UTC, JonasKaad approved these changes

2022-05-23 09:01 UTC, merged